In [1]:
#import the library used to query a website
from urllib.request import urlopen

#specify the url
wiki = "https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic_by_country_and_territory"
wiki2 = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

#Query the website and return the html to the variable 'page'
page = urlopen(wiki)
page2 = urlopen(wiki2)

#import the Beautiful soup functions to parse the data returned from the website
from bs4 import BeautifulSoup

#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page)
soup2 = BeautifulSoup(page2)

In [2]:
right_table=soup.find('table', class_='wikitable plainrowheaders sortable')
right_table2=soup2.find('table', class_='wikitable sortable')

In [3]:
A=[]

for row in right_table.findAll("tr"):
    cells = row.findAll('a')
    #print(cells)
    if len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5 or len(cells)==6:
        if cells[0].find(text=True) == None:
            A.append(cells[1].find(text=True))
        else:
            A.append(cells[0].find(text=True))
    
del(A[0])
del(A[1])
del(A[-1])
A[0] = 'China'

In [4]:
A2=[]

for row in right_table2.findAll("tr"):
    cells = row.findAll('a')
    if len(cells)==1 or len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5:
        if cells[0].find(text=True) == None:
            A2.append(cells[1].find(text=True))
        else:
            A2.append(cells[0].find(text=True))
    
del(A2[-1])

#Generate lists
B2=[]


for row in right_table2.findAll("tr"):
    cells = row.findAll("td")
    if len(cells)==6: #Only extract table body not heading
        B2.append(cells[2].find(text=True))

In [5]:
#Generate lists
B=[]
C=[]
D=[]

for row in right_table.findAll("tr"):
    cells = row.findAll("td")
    if len(cells)==4: #Only extract table body not heading
        B.append(cells[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))

In [6]:
print(len(D))

154

In [7]:
G=[]

for i,country in enumerate(A):
    if A[i] in A2:
        idx = A2.index(A[i])
        population = B2[idx]
        G.append(population)
    else:
        G.append('-')

In [8]:
print(len(A))
print(A)

154
['China', 'Italy', 'Iran', 'Spain', 'Germany', 'France', 'South Korea', 'United States', 'Switzerland', 'United Kingdom', 'Netherlands', 'Austria', 'Norway', 'Belgium', 'Sweden', 'Denmark', 'Japan', 'Malaysia', 'Diamond Princess', 'Portugal', 'Canada', 'Australia', 'Czech Republic', 'Qatar', 'Israel', 'Greece', 'Brazil', 'Finland', 'Singapore', 'Pakistan', 'Ireland', 'Poland', 'Slovenia', 'Romania', 'Estonia', 'Iceland', 'Bahrain', 'Chile', 'Indonesia', 'Thailand', 'Luxembourg', 'Egypt', 'Philippines', 'Hong Kong', 'Saudi Arabia', 'Iraq', 'Ecuador', 'India', 'Russia', 'Peru', 'Kuwait', 'Lebanon', 'San Marino', 'South Africa', 'United Arab Emirates', 'Armenia', 'Slovakia', 'Taiwan', 'Turkey', 'Colombia', 'Mexico', 'Bulgaria', 'Serbia', 'Croatia', 'Panama', 'Argentina', 'Vietnam', 'Algeria', 'Latvia', 'Brunei', 'Albania', 'Hungary', 'Jordan', 'Belarus', 'Sri Lanka', 'Costa Rica', 'Uruguay', 'Cyprus', 'Morocco', 'Malta', 'Palestine', 'Andorra', 'Bosnia and Herzegovina', 'Georgia', 'North Macedonia', 'Venezuela', 'Cambodia', 'Kazakhstan', 'Azerbaijan', 'Lithuania', 'Oman', 'Senegal', 'Moldova', 'Tunisia', 'Afghanistan', 'Dominican Republic', 'Burkina Faso', 'New Zealand', 'Northern Cyprus', 'Liechtenstein', 'Macau', 'Uzbekistan', 'Ukraine', 'Bangladesh', 'Jamaica', 'Maldives', 'Kosovo', 'Bolivia', 'Guyana', 'Paraguay', 'Cameroon', 'Cuba', 'Honduras', 'Monaco', 'Guatemala', 'Nigeria', 'Rwanda', 'DR Congo', 'Kenya', 'Trinidad and Tobago', 'Ethiopia', 'Ghana', 'Ivory Coast', 'Mongolia', 'Seychelles', 'Kyrgyzstan', 'Mauritius', 'Tanzania', 'Barbados', 'Benin', 'Liberia', 'Montenegro', 'Namibia', 'Saint Lucia', 'Sudan', 'Zambia', 'Antigua and Barbuda', 'Bahamas', 'Bhutan', 'Central African Republic', 'Republic of the Congo', 'Djibouti', 'Equatorial Guinea', 'Eswatini', 'Gabon', 'Gambia', 'Guinea', 'Mauritania', 'St. Vincent ', 'Somalia', 'Suriname', 'Togo', 'Vatican City', 'Nepal']

In [9]:
E=[]
F=[]
H=[]

for i in range(len(B)):
    rate = int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100/int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
    exist = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(D[i]).replace('\n', '').replace('\r', '').replace(',', '').replace('â€“', '0').encode('utf8'))
    rate = round(rate, 3)
    E.append(rate)
    exist = format(exist, ',')
    F.append(exist)
    if G[i] != '-':
        rate10k = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100000/int(str(G[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        rate10k = round(rate10k, 3)
        H.append(rate10k)
    else:
        H.append('-')

In [10]:
#import pandas to convert list to data frame

import pandas as pd


df=pd.DataFrame(A,columns=['Location'])

df['Cases']=B

df['Deaths']=C

df['Recoveries']=D

df['Death rate (%)']=E

df['Existing cases']=F

df['Population']=G

df['Infected per 100,000']=H

df.to_excel("Corona_statistics.xlsx")


df[:60]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
0,China,"80,894","3,237","69,614",4.002,"8,043","1,401,812,360",5.771
1,Italy,"35,713","2,978","4,025",8.339,"28,710","60,243,406",59.281
2,Iran,"17,361","1,135","5,710",6.538,"10,516","83,290,141",20.844
3,Spain,"14,746",638,"1,081",4.327,"13,027","47,100,396",31.308
4,Germany,"11,979",28,105,0.234,"11,846","83,149,300",14.407
5,France,"9,134",264,602,2.890,"8,268","67,069,000",13.619
6,South Korea,"8,413",84,"1,540",0.998,"6,789","51,780,579",16.247
7,United States,"8,034",124,106,1.543,"7,804","329,470,935",2.438
8,Switzerland,"3,070",27,15,0.879,"3,028","8,586,550",35.754
9,United Kingdom,"2,630",104,65,3.954,"2,461","66,435,600",3.959
10,Netherlands,"2,059",58,â€“,2.817,"2,001","17,445,781",11.802
11,Austria,"1,646",4,9,0.243,"1,633","8,902,600",18.489
12,Norway,"1,557",6,1,0.385,"1,550","5,367,580",29.007
13,Belgium,"1,486",14,31,0.942,"1,441","11,524,454",12.894
14,Sweden,"1,279",10,1,0.782,"1,268","10,333,456",12.377
15,Denmark,"1,117",4,â€“,0.358,"1,113","5,822,763",19.183
16,Japan,899,29,144,3.226,726,"126,010,000",0.713
17,Malaysia,790,2,60,0.253,728,"32,722,760",2.414
18,Diamond Princess,712,7,527,0.983,178,-,-
19,Portugal,642,2,3,0.312,637,"10,276,617",6.247
20,Canada,644,9,12,1.398,623,"37,961,548",1.696
21,Australia,565,6,43,1.062,516,"25,649,909",2.203
22,Czech Republic,464,0,3,0.000,461,"10,681,161",4.344
23,Qatar,452,0,4,0.000,448,"2,747,282",16.453
24,Israel,433,0,11,0.000,422,"9,173,250",4.72
25,Greece,418,5,14,1.196,399,"10,724,599",3.898
26,Brazil,387,3,2,0.775,382,"211,270,518",0.183
27,Finland,359,0,10,0.000,349,"5,527,573",6.495
28,Singapore,313,0,117,0.000,196,"5,703,600",5.488
29,Pakistan,299,2,2,0.669,295,"218,983,520",0.137
30,Ireland,292,2,5,0.685,285,"4,921,500",5.933
31,Poland,287,5,1,1.742,281,"38,386,000",0.748
32,Slovenia,286,1,0,0.350,285,"2,094,060",13.658
33,Romania,260,0,19,0.000,241,"19,405,156",1.34
34,Estonia,258,0,1,0.000,257,"1,328,360",19.422
35,Iceland,250,0,5,0.000,245,"364,260",68.632
36,Bahrain,242,1,88,0.413,153,"1,543,300",15.681
37,Chile,238,0,0,0.000,238,"19,107,216",1.246
38,Indonesia,227,19,11,8.370,197,"266,911,900",0.085
39,Thailand,212,1,42,0.472,169,"66,482,792",0.319
40,Luxembourg,203,2,0,0.985,201,"613,894",33.068
41,Egypt,196,6,32,3.061,158,"100,138,465",0.196
42,Philippines,193,14,4,7.254,175,"108,420,484",0.178
43,Hong Kong,181,4,92,2.210,85,"7,500,700",2.413
44,Saudi Arabia,171,0,6,0.000,165,"34,218,169",0.5
45,Iraq,164,12,41,7.317,111,"39,127,900",0.419
46,Ecuador,155,2,0,1.290,153,"17,446,584",0.888
47,India,151,3,14,1.987,134,"1,359,933,123",0.011
48,Russia,147,0,5,0.000,142,"146,745,098",0.1
49,Peru,145,0,1,0.000,144,"32,131,400",0.451
50,Kuwait,142,0,15,0.000,127,"4,420,110",3.213
51,Lebanon,133,4,4,3.008,125,"6,825,442",1.949
52,San Marino,119,11,4,9.244,104,"33,574",354.441
53,South Africa,116,0,0,0.000,116,"58,775,022",0.197
54,United Arab Emirates,113,0,26,0.000,87,"9,890,400",1.143
55,Armenia,110,0,1,0.000,109,"2,957,500",3.719
56,Slovakia,105,0,0,0.000,105,"5,456,362",1.924
57,Taiwan,100,1,22,1.000,77,"23,604,265",0.424
58,Turkey,98,1,0,1.020,97,"83,154,997",0.118
59,Colombia,93,0,1,0.000,92,"49,395,678",0.188

In [11]:
df[60:120]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
60,Mexico,93,0,4,0.000,89,"126,577,691",0.073
61,Bulgaria,92,2,0,2.174,90,"7,000,039",1.314
62,Serbia,89,0,1,0.000,88,"6,963,764",1.278
63,Croatia,87,0,5,0.000,82,"4,076,246",2.134
64,Panama,86,1,0,1.163,85,"4,218,808",2.038
65,Argentina,79,2,3,2.532,74,"44,938,712",0.176
66,Vietnam,76,0,16,0.000,60,"96,208,984",0.079
67,Algeria,72,5,10,6.944,57,"43,000,000",0.167
68,Latvia,71,0,1,0.000,70,"1,906,800",3.724
69,Brunei,68,0,0,0.000,68,"442,400",15.371
70,Albania,59,2,0,3.390,57,"2,862,427",2.061
71,Hungary,58,1,2,1.724,55,"9,772,756",0.593
72,Jordan,56,0,1,0.000,55,"10,638,536",0.526
73,Belarus,51,0,5,0.000,46,"9,413,446",0.542
74,Sri Lanka,51,0,3,0.000,48,"21,803,000",0.234
75,Costa Rica,50,0,0,0.000,50,"5,058,007",0.989
76,Uruguay,50,0,0,0.000,50,"3,518,552",1.421
77,Cyprus,49,0,0,0.000,49,"875,900",5.594
78,Morocco,49,2,1,4.082,46,"35,842,238",0.137
79,Malta,48,0,2,0.000,46,"493,559",9.725
80,Palestine,44,0,0,0.000,44,"4,976,684",0.884
81,Andorra,39,0,1,0.000,38,"77,543",50.295
82,Bosnia and Herzegovina,39,0,2,0.000,37,"3,301,000",1.181
83,Georgia,38,0,1,0.000,37,"3,723,464",1.021
84,North Macedonia,36,0,1,0.000,35,"2,077,132",1.733
85,Venezuela,36,0,0,0.000,36,"32,219,521",0.112
86,Cambodia,35,0,1,0.000,34,"15,288,489",0.229
87,Kazakhstan,35,0,0,0.000,35,"18,665,232",0.188
88,Azerbaijan,34,1,10,2.941,23,"10,067,108",0.338
89,Lithuania,33,0,1,0.000,32,"2,793,350",1.181
90,Oman,33,0,12,0.000,21,"4,664,790",0.707
91,Senegal,31,0,2,0.000,29,"16,209,125",0.191
92,Moldova,30,1,1,3.333,28,"2,681,735",1.119
93,Tunisia,29,0,0,0.000,29,"11,722,038",0.247
94,Afghanistan,22,0,1,0.000,21,"32,225,560",0.068
95,Dominican Republic,21,1,0,4.762,20,"10,358,320",0.203
96,Burkina Faso,20,1,0,5.000,19,"20,870,060",0.096
97,New Zealand,20,0,0,0.000,20,"4,971,205",0.402
98,Northern Cyprus,20,0,0,0.000,20,"351,965",5.682
99,Liechtenstein,19,0,0,0.000,19,"38,749",49.034
100,Macau,15,0,10,0.000,5,"679,600",2.207
101,Uzbekistan,15,0,0,0.000,15,"34,075,852",0.044
102,Ukraine,14,2,0,14.286,12,"41,902,416",0.033
103,Bangladesh,14,1,3,7.143,10,"168,287,530",0.008
104,Jamaica,13,0,2,0.000,11,"2,726,667",0.477
105,Maldives,13,0,0,0.000,13,"374,775",3.469
106,Kosovo,13,0,0,0.000,13,"1,795,666",0.724
107,Bolivia,12,0,0,0.000,12,"11,469,896",0.105
108,Guyana,11,1,0,9.091,10,"782,766",1.405
109,Paraguay,11,0,0,0.000,11,"7,152,703",0.154
110,Cameroon,10,0,0,0.000,10,"26,545,864",0.038
111,Cuba,10,0,0,0.000,10,"11,209,628",0.089
112,Honduras,9,0,0,0.000,9,"9,158,345",0.098
113,Monaco,9,0,0,0.000,9,"38,300",23.499
114,Guatemala,8,1,0,12.500,7,"16,604,026",0.048
115,Nigeria,8,0,1,0.000,7,"206,139,587",0.004
116,Rwanda,8,0,0,0.000,8,"12,374,397",0.065
117,DR Congo,7,0,0,0.000,7,"89,561,404",0.008
118,Kenya,7,0,0,0.000,7,"47,564,296",0.015
119,Trinidad and Tobago,7,0,0,0.000,7,"1,363,985",0.513

In [12]:
df[120:-1]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
120,Ethiopia,6,0,0,0.0,6,"98,665,000",0.006
121,Ghana,6,0,0,0.0,6,"30,280,811",0.02
122,Ivory Coast,6,0,1,0.0,5,"25,823,071",0.023
123,Mongolia,6,0,0,0.0,6,"3,308,132",0.181
124,Seychelles,4,0,0,0.0,4,"97,625",4.097
125,Kyrgyzstan,3,0,0,0.0,3,"6,523,500",0.046
126,Mauritius,3,0,0,0.0,3,"1,265,985",0.237
127,Tanzania,3,0,0,0.0,3,"55,890,747",0.005
128,Barbados,2,0,0,0.0,2,"287,025",0.697
129,Benin,2,0,0,0.0,2,"11,733,059",0.017
130,Liberia,2,0,0,0.0,2,"4,475,353",0.045
131,Montenegro,2,0,0,0.0,2,"622,359",0.321
132,Namibia,2,0,0,0.0,2,"2,458,936",0.081
133,Saint Lucia,2,0,0,0.0,2,"178,696",1.119
134,Sudan,2,1,0,50.0,1,"42,353,615",0.005
135,Zambia,2,0,0,0.0,2,"17,381,168",0.012
136,Antigua and Barbuda,1,0,0,0.0,1,"96,453",1.037
137,Bahamas,1,0,0,0.0,1,"385,340",0.26
138,Bhutan,1,0,0,0.0,1,"741,672",0.135
139,Central African Republic,1,0,0,0.0,1,"5,496,011",0.018
140,Republic of the Congo,1,0,0,0.0,1,-,-
141,Djibouti,1,0,0,0.0,1,"1,078,373",0.093
142,Equatorial Guinea,1,0,0,0.0,1,"1,358,276",0.074
143,Eswatini,1,0,0,0.0,1,"1,093,238",0.091
144,Gabon,1,0,0,0.0,1,"2,172,579",0.046
145,Gambia,1,0,0,0.0,1,"2,347,706",0.043
146,Guinea,1,0,0,0.0,1,"12,218,357",0.008
147,Mauritania,1,0,0,0.0,1,"4,077,347",0.025
148,St. Vincent,1,0,0,0.0,1,-,-
149,Somalia,1,0,0,0.0,1,"15,893,219",0.006
150,Suriname,1,0,0,0.0,1,"581,372",0.172
151,Togo,1,0,0,0.0,1,"7,538,000",0.013
152,Vatican City,1,0,0,0.0,1,799,125.156

In [13]:
d = {}

for i in range(len(A)):
    d[A[i]] = (B[i],C[i],D[i],E[i],F[i],G[i],H[i])