In [1]:
#import the library used to query a website
from urllib.request import urlopen

#specify the url
wiki = "https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic_by_country_and_territory"
wiki2 = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

#Query the website and return the html to the variable 'page'
page = urlopen(wiki)
page2 = urlopen(wiki2)

#import the Beautiful soup functions to parse the data returned from the website
from bs4 import BeautifulSoup

#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page)
soup2 = BeautifulSoup(page2)

In [2]:
right_table=soup.find('table', class_='wikitable plainrowheaders sortable')
right_table2=soup2.find('table', class_='wikitable sortable')

In [3]:
A=[]

for row in right_table.findAll("tr"):
    cells = row.findAll('th')
    #print(cells)
    if len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5 or len(cells)==6:
        if cells[0].find(text=True) == None:
            A.append(cells[1].find(text=True))
        else:
            A.append(cells[1].find(text=True))
    
del(A[0])
del(A[0])
#del(A[-1])
A3 = []
for i in range(len(A)):
    A3.append(str(A[i]).replace('\n', '').replace('\r', '').replace('China ', 'China'))

In [4]:
A2=[]

for row in right_table2.findAll("tr"):
    cells = row.findAll('a')
    if len(cells)==1 or len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5:
        if cells[0].find(text=True) == None:
            A2.append(cells[1].find(text=True))
        else:
            A2.append(cells[0].find(text=True))
    
del(A2[-1])

#Generate lists
B2=[]


for row in right_table2.findAll("tr"):
    cells = row.findAll("td")
    if len(cells)==6: #Only extract table body not heading
        B2.append(cells[2].find(text=True))

In [5]:
#Generate lists
B=[]
C=[]
D=[]

for row in right_table.findAll("tr"):
    cells = row.findAll("td")
    #print(cells)
    if len(cells)==4: #Only extract table body not heading
        B.append(cells[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))

In [6]:
G=[]

for i,country in enumerate(A3):
    if A3[i] in A2:
        idx = A2.index(A3[i])
        population = B2[idx]
        G.append(population)
    else:
        G.append('-')

In [7]:
E=[]
F=[]
H=[]

for i in range(len(B)):
    if str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit() and str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit():
        rate = int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100/int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        exist = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(D[i]).replace('\n', '').replace('\r', '').replace(',', '').replace('–', '0').encode('utf8'))
        exist = format(exist, ',')
        rate = round(rate, 3)
    else:
        rate = '-'
        exist = '-'
    E.append(rate)
    
    F.append(exist)
    if G[i] != '-' and str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit():
        rate10k = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100000/int(str(G[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        rate10k = round(rate10k, 3)
        H.append(rate10k)
    else:
        H.append('-')

In [8]:
#import pandas to convert list to data frame

import pandas as pd


df=pd.DataFrame(A3,columns=['Location'])

df['Cases']=B

df['Deaths']=C

df['Recoveries']=D

df['Death rate (%)']=E

df['Existing cases']=F

df['Population']=G

df['Infected per 100,000']=H

df.to_excel("Corona_statistics.xlsx")


df[:60]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
0,China,"80,967","3,248","71,150",4.012,"6,569","1,401,826,880",5.776
1,Italy,"41,035","3,405","4,440",8.298,"33,190","60,243,406",68.115
2,Iran,"18,407","1,284","5,979",6.976,"11,144","83,292,869",22.099
3,Spain,"18,077",833,"1,107",4.608,"16,137","47,100,396",38.38
4,Germany,"15,320",44,115,0.287,"15,161","83,149,300",18.425
5,United States,"14,363",218,121,1.518,"14,024","329,476,630",4.359
6,France,"10,995",372,"1,300",3.383,"9,323","67,069,000",16.394
7,South Korea,"8,652",94,"2,233",1.086,"6,325","51,780,579",16.709
8,Switzerland,"3,438",33,15,0.960,"3,390","8,586,550",40.039
9,United Kingdom,"3,280",144,79,4.390,"3,057","66,435,600",4.937
10,Netherlands,"2,469",77,–,3.119,"2,392","17,446,131",14.152
11,Austria,"2,096",6,9,0.286,"2,081","8,902,600",23.544
12,Belgium,"1,795",21,31,1.170,"1,743","11,524,454",15.576
13,Norway,"1,790",7,–,0.391,"1,783","5,367,580",33.348
14,Sweden,"1,423",11,–,0.773,"1,412","10,333,456",13.771
15,Denmark,"1,225",6,–,0.490,"1,219","5,822,763",21.038
16,Japan,963,33,215,3.427,715,"126,010,000",0.764
17,Malaysia,900,2,75,0.222,823,"32,723,760",2.75
18,Canada,872,12,11,1.376,849,"37,962,718",2.297
19,Australia,814,7,46,0.860,761,"25,650,937",3.173
20,Portugal,785,3,3,0.382,779,"10,276,617",7.639
21,Diamond Princess,712,8,551,1.124,153,-,-
22,Czech Republic,694,0,3,0.000,691,"10,681,161",6.497
23,Israel,677,0,12,0.000,665,"9,173,700",7.38
24,Brazil,647,7,2,1.082,638,"211,274,931",0.306
25,Ireland,557,3,5,0.539,549,"4,921,500",11.318
26,Greece,464,6,19,1.293,439,"10,724,599",4.327
27,Qatar,460,0,10,0.000,450,"2,747,282",16.744
28,Pakistan,454,2,13,0.441,439,"218,994,520",0.207
29,Finland,400,0,10,0.000,390,"5,527,573",7.236
30,Turkey,359,4,0,1.114,355,"83,154,997",0.432
31,Poland,355,5,1,1.408,349,"38,386,000",0.925
32,Singapore,345,0,124,0.000,221,"5,703,600",6.049
33,Chile,342,0,0,0.000,342,"19,107,216",1.79
34,Luxembourg,335,4,0,1.194,331,"613,894",54.57
35,Iceland,330,0,5,0.000,325,"364,260",90.595
36,Thailand,322,1,43,0.311,278,"66,483,180",0.484
37,Slovenia,319,1,–,0.313,318,"2,094,060",15.234
38,Indonesia,309,25,15,8.091,269,"266,911,900",0.116
39,Bahrain,279,1,110,0.358,168,"1,543,300",18.078
40,Romania,277,0,25,0.000,252,"19,405,156",1.427
41,Saudi Arabia,274,0,8,0.000,266,"34,218,169",0.801
42,Estonia,267,0,1,0.000,266,"1,328,360",20.1
43,Ecuador,260,4,3,1.538,253,"17,447,260",1.49
44,Egypt,256,7,42,2.734,207,"100,142,312",0.256
45,Peru,234,3,1,1.282,230,"32,131,400",0.728
46,Philippines,217,17,8,7.834,192,"108,424,883",0.2
47,Hong Kong,208,4,98,1.923,106,"7,500,700",2.773
48,Russia,199,0,5,0.000,194,"146,745,098",0.136
49,India,194,4,20,2.062,170,"1,359,973,382",0.014
50,Iraq,192,12,41,6.250,139,"39,127,900",0.491
51,Lebanon,157,4,4,2.548,149,"6,825,442",2.3
52,South Africa,150,0,0,0.000,150,"58,775,022",0.255
53,Kuwait,148,0,18,0.000,130,"4,420,110",3.348
54,San Marino,144,14,4,9.722,126,"33,574",428.903
55,United Arab Emirates,140,0,31,0.000,109,"9,890,400",1.416
56,Panama,137,1,1,0.730,135,"4,218,808",3.247
57,Colombia,128,0,1,0.000,127,"49,395,678",0.259
58,Slovakia,124,0,0,0.000,124,"5,456,362",2.273
59,Armenia,122,0,1,0.000,121,"2,957,500",4.125

In [9]:
df[60:120]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
60,Mexico,118,1,4,0.847,113,"126,577,691",0.093
61,Croatia,110,0,5,0.000,105,"4,076,246",2.699
62,Taiwan,108,1,26,0.926,81,"23,604,265",0.458
63,Bulgaria,105,3,0,2.857,102,"7,000,039",1.5
64,Serbia,103,0,1,0.000,102,"6,963,764",1.479
65,Argentina,97,3,3,3.093,91,"44,938,712",0.216
66,Algeria,90,9,32,10.000,49,"43,000,000",0.209
67,Costa Rica,89,2,0,2.247,87,"5,058,007",1.76
68,Latvia,86,0,1,0.000,85,"1,906,800",4.51
69,Vietnam,85,0,18,0.000,67,"96,208,984",0.088
70,Uruguay,79,0,0,0.000,79,"3,518,552",2.245
71,Andorra,74,0,1,0.000,73,"77,543",95.431
72,Brunei,73,0,0,0.000,73,"442,400",16.501
73,Hungary,73,1,2,1.370,70,"9,772,756",0.747
74,Jordan,69,0,1,0.000,68,"10,639,260",0.649
75,Cyprus,67,0,0,0.000,67,"875,900",7.649
76,Albania,64,2,0,3.125,62,"2,862,427",2.236
77,Bosnia and Herzegovina,64,0,2,0.000,62,"3,301,000",1.939
78,Morocco,63,2,2,3.175,59,"35,843,203",0.176
79,Sri Lanka,60,0,3,0.000,57,"21,803,000",0.275
80,Malta,53,0,2,0.000,51,"493,559",10.738
81,Belarus,51,0,5,0.000,46,"9,413,446",0.542
82,North Macedonia,50,0,1,0.000,49,"2,077,132",2.407
83,Moldova,49,1,1,2.041,47,"2,681,735",1.827
84,Kazakhstan,49,0,0,0.000,49,"18,665,848",0.263
85,Oman,48,0,13,0.000,35,"4,664,790",1.029
86,Cambodia,47,0,1,0.000,46,"15,288,489",0.307
87,Palestine,47,0,0,0.000,47,"4,976,684",0.944
88,Azerbaijan,44,1,10,2.273,33,"10,067,108",0.437
89,Venezuela,42,0,0,0.000,42,"32,219,521",0.13
90,Lithuania,41,0,1,0.000,40,"2,793,350",1.468
91,Georgia,40,0,1,0.000,39,"3,723,464",1.074
92,Tunisia,39,1,1,2.564,37,"11,722,038",0.333
93,New Zealand,39,0,0,0.000,39,"4,971,458",0.784
94,Senegal,36,0,2,0.000,34,"16,209,125",0.222
95,Dominican Republic,34,2,0,5.882,32,"10,358,320",0.328
96,Burkina Faso,33,1,0,3.030,32,"20,870,060",0.158
97,Liechtenstein,28,0,0,0.000,28,"38,749",72.26
98,Honduras,24,0,0,0.000,24,"9,158,345",0.262
99,Uzbekistan,23,0,0,0.000,23,"34,077,711",0.067
100,Afghanistan,22,0,1,0.000,21,"32,225,560",0.068
101,Kosovo,21,0,0,0.000,21,"1,795,666",1.169
102,Bangladesh,18,1,3,5.556,14,"168,293,156",0.011
103,Bolivia,17,0,0,0.000,17,"11,469,896",0.148
104,Macau,17,0,10,0.000,7,"679,600",2.501
105,Ukraine,16,2,0,12.500,14,"41,902,416",0.038
106,Jamaica,15,1,2,6.667,12,"2,726,667",0.55
107,DR Congo,14,0,0,0.000,14,"89,561,404",0.016
108,Cameroon,13,0,0,0.000,13,"26,545,864",0.049
109,Maldives,13,0,0,0.000,13,"374,775",3.469
110,Montenegro,13,0,0,0.000,13,"622,359",2.089
111,Paraguay,13,0,0,0.000,13,"7,152,703",0.182
112,Nigeria,12,0,1,0.000,11,"206,139,587",0.006
113,Cuba,11,1,0,9.091,10,"11,209,628",0.098
114,Ghana,11,0,0,0.000,11,"30,280,811",0.036
115,Rwanda,11,0,0,0.000,11,"12,374,397",0.089
116,Ethiopia,9,0,0,0.000,9,"98,665,000",0.009
117,Guatemala,9,1,0,11.111,8,"16,604,026",0.054
118,Ivory Coast,9,0,1,0.000,8,"25,823,071",0.035
119,Monaco,9,0,0,0.000,9,"38,300",23.499

In [10]:
df[120:-1]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
120,Trinidad and Tobago,9,0,0,0.0,9,"1,363,985",0.66
121,Kenya,7,0,0,0.0,7,"47,564,296",0.015
122,Mauritius,7,0,0,0.0,7,"1,265,985",0.553
123,Equatorial Guinea,6,0,0,0.0,6,"1,358,276",0.442
124,Kyrgyzstan,6,0,0,0.0,6,"6,523,500",0.092
125,Mongolia,6,0,0,0.0,6,"3,308,296",0.181
126,Seychelles,6,0,0,0.0,6,"97,625",6.146
127,Tanzania,6,0,0,0.0,6,"55,890,747",0.011
128,Barbados,5,0,0,0.0,5,"287,025",1.742
129,Guyana,4,1,0,25.0,3,"782,766",0.511
130,Bahamas,3,0,0,0.0,3,"385,340",0.779
131,Republic of the Congo,3,0,0,0.0,3,-,-
132,Gabon,3,0,0,0.0,3,"2,172,579",0.138
133,Namibia,3,0,0,0.0,3,"2,458,936",0.122
134,Benin,2,0,0,0.0,2,"11,733,059",0.017
135,Bhutan,2,0,0,0.0,2,"741,672",0.27
136,Haiti,2,0,0,0.0,2,"11,577,779",0.017
137,Liberia,2,0,0,0.0,2,"4,475,353",0.045
138,Mauritania,2,0,0,0.0,2,"4,077,347",0.049
139,Saint Lucia,2,0,0,0.0,2,"178,696",1.119
140,Sudan,2,1,0,50.0,1,"42,356,250",0.005
141,Zambia,2,0,0,0.0,2,"17,381,168",0.012
142,Angola,1,0,0,0.0,1,"31,127,674",0.003
143,Antigua and Barbuda,1,0,0,0.0,1,"96,453",1.037
144,Cabo Verde,1,0,0,0.0,1,-,-
145,Chad,1,0,0,0.0,1,"15,692,969",0.006
146,Central African Republic,1,0,0,0.0,1,"5,496,011",0.018
147,Djibouti,1,0,0,0.0,1,"1,078,373",0.093
148,El Salvador,1,0,0,0.0,1,"6,486,201",0.015
149,Eswatini,1,0,0,0.0,1,"1,093,238",0.091
150,Fiji,1,0,0,0.0,1,"884,887",0.113
151,Gambia,1,0,0,0.0,1,"2,347,706",0.043
152,Guinea,1,0,0,0.0,1,"12,218,357",0.008
153,Nepal,1,0,1,0.0,0,"29,609,623",0.003
154,Niger,1,0,0,0.0,1,"22,314,743",0.004
155,Nicaragua,1,0,0,0.0,1,"6,460,411",0.015
156,St. Vincent,1,0,0,0.0,1,-,-
157,Somalia,1,0,0,0.0,1,"15,893,219",0.006
158,Suriname,1,0,0,0.0,1,"581,372",0.172
159,Togo,1,0,0,0.0,1,"7,538,000",0.013

In [11]:
d = {}

for i in range(len(A)):
    d[A[i]] = (B[i],C[i],D[i],E[i],F[i],G[i],H[i])