In [1]:
#import the library used to query a website
from urllib.request import urlopen

#specify the url
wiki = "https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic"
wiki2 = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

#Query the website and return the html to the variable 'page'
page = urlopen(wiki)
page2 = urlopen(wiki2)

#import the Beautiful soup functions to parse the data returned from the website
from bs4 import BeautifulSoup

#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page)
soup2 = BeautifulSoup(page2)

In [2]:
right_table=soup.find('table', class_='wikitable plainrowheaders sortable')
right_table2=soup2.find('table', class_='wikitable sortable')

In [3]:
A=[]

for row in right_table.findAll("tr"):
    cells = row.findAll('th')
    #print(cells)
    if len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5 or len(cells)==6:
        if cells[0].find(text=True) == None:
            A.append(cells[1].find(text=True))
        else:
            A.append(cells[1].find(text=True))
    
del(A[0])
del(A[0])
#del(A[-1])
A3 = []
for i in range(len(A)):
    A3.append(str(A[i]).replace('\n', '').replace('\r', '').replace('China ', 'China'))

In [4]:
A2=[]

for row in right_table2.findAll("tr"):
    cells = row.findAll('a')
    if len(cells)==1 or len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5:
        if cells[0].find(text=True) == None:
            A2.append(cells[1].find(text=True))
        else:
            A2.append(cells[0].find(text=True))
    
del(A2[-1])

#Generate lists
B2=[]


for row in right_table2.findAll("tr"):
    cells = row.findAll("td")
    if len(cells)==6: #Only extract table body not heading
        B2.append(cells[2].find(text=True))

In [5]:
#Generate lists
B=[]
C=[]
D=[]

for row in right_table.findAll("tr"):
    cells = row.findAll("td")
    #print(cells)
    if len(cells)==4 or len(cells)==5: #Only extract table body not heading
        B.append(cells[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))

In [6]:
G=[]

for i,country in enumerate(A3):
    if A3[i] in A2:
        idx = A2.index(A3[i])
        population = B2[idx]
        G.append(population)
    else:
        G.append('-')

In [7]:
E=[]
F=[]
H=[]

for i in range(len(B)):
    if str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit() and str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit():
        rate = int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100/int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        exist = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(D[i]).replace('\n', '').replace('\r', '').replace(',', '').replace('â€“', '0').encode('utf8'))
        exist = format(exist, ',')
        rate = round(rate, 3)
    else:
        rate = '-'
        exist = '-'
    E.append(rate)
    
    F.append(exist)
    if G[i] != '-' and str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit():
        rate10k = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100000/int(str(G[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        rate10k = round(rate10k, 3)
        H.append(rate10k)
    else:
        H.append('-')

In [8]:
#import pandas to convert list to data frame

import pandas as pd

df=pd.DataFrame(A3,columns=['Location'])

df['Cases']=B

df['Deaths']=C

df['Recoveries']=D

df['Death rate (%)']=E

df['Existing cases']=F

df['Population']=G

df['Infected per 100,000']=H

df.to_excel("Corona_statistics.xlsx")


df[:60]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
0,China,"81,093","3,270","72,703",4.032,"5,120","1,401,855,920",5.785
1,Italy,"59,138","5,476","7,024",9.260,"46,638","60,243,406",98.165
2,United States,"35,418",473,175,1.335,"34,770","329,488,021",10.749
3,Spain,"33,089","2,182","3,355",6.594,"27,552","47,100,396",70.252
4,Germany,"26,220",111,266,0.423,"25,843","83,149,300",31.534
5,Iran,"21,638","1,812","7,913",8.374,"11,913","83,298,325",25.977
6,France,"16,018",674,"2,200",4.208,"13,144","67,069,000",23.883
7,South Korea,"8,961",111,"3,166",1.239,"5,684","51,780,579",17.306
8,Switzerland,"8,249",107,131,1.297,"8,011","8,586,550",96.069
9,United Kingdom,"5,702",282,140,4.946,"5,280","66,435,600",8.583
10,Netherlands,"4,216",180,â€“,4.269,"4,036","17,446,831",24.165
11,Austria,"3,784",16,9,0.423,"3,759","8,902,600",42.504
12,Belgium,"3,743",88,350,2.351,"3,305","11,524,454",32.479
13,Norway,"2,415",8,â€“,0.331,"2,407","5,367,580",44.992
14,Portugal,"2,060",23,14,1.117,"2,023","10,276,617",20.046
15,Sweden,"1,934",24,16,1.241,"1,894","10,333,456",18.716
16,Australia,"1,709",7,88,0.410,"1,614","25,652,995",6.662
17,Brazil,"1,619",25,2,1.544,"1,592","211,283,757",0.766
18,Denmark,"1,572",13,â€“,0.827,"1,559","5,822,763",26.997
19,Malaysia,"1,518",14,159,0.922,"1,345","32,725,760",4.639
20,Canada,"1,472",21,18,1.427,"1,433","37,965,057",3.877
21,Israel,"1,238",1,37,0.081,"1,200","9,174,600",13.494
22,Turkey,"1,236",30,0,2.427,"1,206","83,154,997",1.486
23,Czech Republic,"1,165",1,6,0.086,"1,158","10,693,939",10.894
24,Japan,"1,101",41,235,3.724,825,"126,010,000",0.874
25,Ireland,906,4,5,0.442,897,"4,921,500",18.409
26,Pakistan,803,6,6,0.747,791,"219,016,520",0.367
27,Luxembourg,798,8,6,1.003,784,"613,894",129.99
28,Ecuador,789,14,3,1.774,772,"17,448,612",4.522
29,Thailand,721,1,52,0.139,668,"66,483,955",1.084
30,Diamond Princess,712,9,574,1.264,129,-,-
31,Poland,649,7,1,1.079,641,"38,386,000",1.691
32,Chile,632,1,8,0.158,623,"19,107,216",3.308
33,Finland,626,1,10,0.160,615,"5,527,573",11.325
34,Greece,624,17,19,2.724,588,"10,724,599",5.818
35,Indonesia,579,49,30,8.463,500,"266,911,900",0.217
36,Romania,576,5,73,0.868,498,"19,405,156",2.968
37,Iceland,568,1,36,0.176,531,"364,260",155.933
38,Saudi Arabia,511,0,18,0.000,493,"34,218,169",1.493
39,Singapore,509,2,152,0.393,355,"5,703,600",8.924
40,Qatar,494,0,33,0.000,461,"2,747,282",17.981
41,Philippines,462,33,18,7.143,411,"108,433,682",0.426
42,Russia,438,0,17,0.000,421,"146,745,098",0.298
43,India,433,7,24,1.617,402,"1,360,053,900",0.032
44,Slovenia,414,3,â€“,0.725,411,"2,094,060",19.77
45,South Africa,402,0,2,0.000,400,"58,775,022",0.684
46,Peru,363,5,1,1.377,357,"32,131,400",1.13
47,Hong Kong,356,4,100,1.124,252,"7,500,700",4.746
48,Estonia,352,0,4,0.000,348,"1,328,360",26.499
49,Bahrain,339,2,160,0.590,177,"1,543,300",21.966
50,Egypt,327,14,56,4.281,257,"100,150,004",0.327
51,Mexico,316,2,4,0.633,310,"126,577,691",0.25
52,Panama,313,3,1,0.958,309,"4,218,808",7.419
53,Croatia,306,0,5,0.000,301,"4,076,246",7.507
54,Argentina,266,4,27,1.504,235,"44,938,712",0.592
55,Iraq,266,23,62,8.647,181,"39,127,900",0.68
56,Lebanon,256,4,8,1.562,244,"6,825,442",3.751
57,Colombia,235,2,3,0.851,230,"49,395,678",0.476
58,Serbia,222,2,2,0.901,218,"6,963,764",3.188
59,Dominican Republic,202,3,0,1.485,199,"10,358,320",1.95

In [9]:
df[60:120]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
60,Algeria,201,17,65,8.458,119,"43,000,000",0.467
61,Taiwan,195,2,29,1.026,164,"23,604,265",0.826
62,Armenia,194,0,2,0.000,192,"2,957,500",6.56
63,Kuwait,189,0,30,0.000,159,"4,420,110",4.276
64,Bulgaria,187,3,3,1.604,181,"7,000,039",2.671
65,Slovakia,185,0,7,0.000,178,"5,456,362",3.391
66,Latvia,180,0,1,0.000,179,"1,906,800",9.44
67,San Marino,175,20,4,11.429,151,"33,574",521.237
68,Hungary,167,7,16,4.192,144,"9,772,756",1.709
69,Lithuania,154,1,1,0.649,152,"2,793,471",5.513
70,United Arab Emirates,153,2,38,1.307,113,"9,890,400",1.547
71,North Macedonia,136,2,1,1.471,133,"2,077,132",6.547
72,Uruguay,135,0,0,0.000,135,"3,518,552",3.837
73,Costa Rica,134,2,2,1.493,130,"5,058,007",2.649
74,Morocco,134,4,3,2.985,127,"35,845,131",0.374
75,Bosnia and Herzegovina,128,1,2,0.781,125,"3,301,000",3.878
76,Vietnam,122,0,17,0.000,105,"96,208,984",0.127
77,Andorra,112,1,1,0.893,110,"77,543",144.436
78,Jordan,112,0,1,0.000,111,"10,640,708",1.053
79,Malta,107,0,2,0.000,105,"493,559",21.679
80,New Zealand,102,0,0,0.000,102,"4,971,963",2.052
81,Burkina Faso,99,4,5,4.040,90,"20,870,060",0.474
82,Moldova,94,1,2,1.064,91,"2,681,735",3.505
83,Brunei,91,0,2,0.000,89,"442,400",20.57
84,Albania,89,2,3,2.247,84,"2,862,427",3.109
85,Tunisia,89,3,1,3.371,85,"11,722,038",0.759
86,Cambodia,86,0,2,0.000,84,"15,288,489",0.563
87,Sri Lanka,86,0,3,0.000,83,"21,803,000",0.394
88,Belarus,81,0,22,0.000,59,"9,413,446",0.86
89,Venezuela,77,0,15,0.000,62,"32,219,521",0.239
90,Cyprus,75,0,0,0.000,75,"875,900",8.563
91,Ukraine,73,3,1,4.110,69,"41,902,416",0.174
92,Azerbaijan,72,1,10,1.389,61,"10,067,108",0.715
93,Senegal,67,0,5,0.000,62,"16,209,125",0.413
94,Oman,66,0,17,0.000,49,"4,664,790",1.415
95,Kazakhstan,62,0,0,0.000,62,"18,667,080",0.332
96,Palestine,59,0,17,0.000,42,"4,976,684",1.186
97,Cameroon,56,0,2,0.000,54,"26,545,864",0.211
98,Georgia,54,0,8,0.000,46,"3,723,464",1.45
99,Trinidad and Tobago,50,0,0,0.000,50,"1,363,985",3.666
100,Liechtenstein,46,0,0,0.000,46,"38,749",118.713
101,Uzbekistan,46,0,0,0.000,46,"34,081,430",0.135
102,Afghanistan,40,1,1,2.500,38,"32,225,560",0.124
103,Northern Cyprus,38,0,3,0.000,35,"351,965",10.797
104,Nigeria,36,1,2,2.778,33,"206,139,587",0.017
105,Cuba,35,1,0,2.857,34,"11,209,628",0.312
106,Kosovo,31,0,0,0.000,31,"1,795,666",1.726
107,DR Congo,30,2,0,6.667,28,"89,561,404",0.033
108,Bangladesh,27,2,3,7.407,22,"168,304,408",0.016
109,Honduras,26,0,0,0.000,26,"9,158,345",0.284
110,Ivory Coast,25,0,1,0.000,24,"25,823,071",0.097
111,Bolivia,24,0,0,0.000,24,"11,469,896",0.209
112,Ghana,24,1,0,4.167,23,"30,280,811",0.079
113,Mauritius,24,2,0,8.333,22,"1,265,985",1.896
114,Monaco,23,0,1,0.000,22,"38,300",60.052
115,Montenegro,22,1,0,4.545,21,"622,359",3.535
116,Paraguay,22,1,0,4.545,21,"7,152,703",0.308
117,Guernsey,20,0,0,0.000,20,"62,792",31.851
118,Guatemala,19,1,0,5.263,18,"16,604,026",0.114
119,Jamaica,19,1,2,5.263,16,"2,726,667",0.697

In [10]:
df[120:]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
120,Macau,19,0,10,0.000,9,"679,600",2.796
121,Rwanda,19,0,0,0.000,19,"12,374,397",0.154
122,Togo,18,0,0,0.000,18,"7,538,000",0.239
123,Jersey,15,0,0,0.000,15,"106,800",14.045
124,Kenya,15,0,0,0.000,15,"47,564,296",0.032
125,Barbados,14,0,0,0.000,14,"287,025",4.878
126,Kyrgyzstan,14,0,0,0.000,14,"6,523,500",0.215
127,Maldives,13,0,3,0.000,10,"374,775",3.469
128,Madagascar,12,0,0,0.000,12,"25,680,342",0.047
129,Tanzania,12,0,0,0.000,12,"55,890,747",0.021
130,Ethiopia,11,0,0,0.000,11,"98,665,000",0.011
131,Mongolia,10,0,0,0.000,10,"3,308,624",0.302
132,Seychelles,7,0,0,0.000,7,"97,625",7.17
133,Equatorial Guinea,6,0,0,0.000,6,"1,358,276",0.442
134,Gabon,5,1,0,20.000,4,"2,172,579",0.23
135,Guyana,5,1,0,20.000,4,"782,766",0.639
136,Isle of Man,5,0,0,0.000,5,"83,314",6.001
137,Suriname,5,0,0,0.000,5,"581,372",0.86
138,Bahamas,4,0,0,0.000,4,"385,340",1.038
139,Eswatini,4,0,0,0.000,4,"1,093,238",0.366
140,Guinea,4,0,1,0.000,3,"12,218,357",0.033
141,Cape Verde,3,0,0,0.000,3,"550,483",0.545
142,Central African Republic,3,0,0,0.000,3,"5,496,011",0.055
143,Republic of the Congo,3,0,0,0.000,3,-,-
144,El Salvador,3,0,0,0.000,3,"6,486,201",0.046
145,Liberia,3,0,0,0.000,3,"4,475,353",0.067
146,Namibia,3,0,0,0.000,3,"2,458,936",0.122
147,Zambia,3,0,0,0.000,3,"17,381,168",0.017
148,Zimbabwe,3,1,0,33.333,2,"15,159,624",0.02
149,Angola,2,0,0,0.000,2,"31,127,674",0.006
150,Benin,2,0,0,0.000,2,"11,733,059",0.017
151,Bhutan,2,0,0,0.000,2,"741,672",0.27
152,Fiji,3,0,0,0.000,3,"884,887",0.339
153,Gambia,2,1,0,50.000,1,"2,347,706",0.085
154,Haiti,2,0,0,0.000,2,"11,577,779",0.017
155,Mauritania,2,0,0,0.000,2,"4,077,347",0.049
156,Nepal,2,0,1,0.000,1,"29,609,623",0.007
157,Nicaragua,2,0,0,0.000,2,"6,460,411",0.031
158,Niger,2,0,0,0.000,2,"22,314,743",0.009
159,Saint Lucia,2,0,0,0.000,2,"178,696",1.119
160,Sudan,2,1,0,50.000,1,"42,361,520",0.005
161,Antigua and Barbuda,1,0,0,0.000,1,"96,453",1.037
162,Chad,1,0,0,0.000,1,"15,692,969",0.006
163,Dominica,1,0,0,0.000,1,"71,808",1.393
164,Djibouti,1,0,0,0.000,1,"1,078,373",0.093
165,Eritrea,1,0,0,0.000,1,"3,497,117",0.029
166,Grenada,1,0,0,0.000,1,"112,003",0.893
167,Mozambique,1,0,0,0.000,1,"30,066,648",0.003
168,Papua New Guinea,1,0,0,0.000,1,"8,935,000",0.011
169,St. Vincent,1,0,0,0.000,1,-,-
170,Somalia,1,0,0,0.000,1,"15,893,219",0.006
171,Syria,1,0,0,0.000,1,"17,500,657",0.006
172,East Timor,1,0,0,0.000,1,"1,387,149",0.072
173,Uganda,1,0,0,0.000,1,"40,299,300",0.002
174,Vatican City,1,0,0,0.000,1,799,125.156

In [11]:
d = {}

for i in range(len(A)):
    d[A[i]] = (B[i],C[i],D[i],E[i],F[i],G[i],H[i])