In [1]:
#import the library used to query a website
from urllib.request import urlopen

#specify the url
wiki = "https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic_by_country_and_territory"
wiki2 = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

#Query the website and return the html to the variable 'page'
page = urlopen(wiki)
page2 = urlopen(wiki2)

#import the Beautiful soup functions to parse the data returned from the website
from bs4 import BeautifulSoup

#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page)
soup2 = BeautifulSoup(page2)

In [2]:
right_table=soup.find('table', class_='wikitable plainrowheaders sortable')
right_table2=soup2.find('table', class_='wikitable sortable')

In [3]:
A=[]

for row in right_table.findAll("tr"):
    cells = row.findAll('a')
    #print(cells)
    if len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5:
        if cells[0].find(text=True) == None:
            A.append(cells[1].find(text=True))
        else:
            A.append(cells[0].find(text=True))
    
del(A[0])
del(A[-1])
A[0] = 'China'

In [4]:
A2=[]

for row in right_table2.findAll("tr"):
    cells = row.findAll('a')
    if len(cells)==1 or len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5:
        if cells[0].find(text=True) == None:
            A2.append(cells[1].find(text=True))
        else:
            A2.append(cells[0].find(text=True))
    
del(A2[-1])

#Generate lists
B2=[]


for row in right_table2.findAll("tr"):
    cells = row.findAll("td")
    if len(cells)==6: #Only extract table body not heading
        B2.append(cells[2].find(text=True))

In [5]:
#Generate lists
B=[]
C=[]
D=[]

for row in right_table.findAll("tr"):
    cells = row.findAll("td")
    if len(cells)==4: #Only extract table body not heading
        B.append(cells[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))

In [6]:
G=[]

for i,country in enumerate(A):
    if A[i] in A2:
        idx = A2.index(A[i])
        population = B2[idx]
        G.append(population)
    else:
        G.append("-")

In [7]:
E=[]
F=[]
H=[]

for i in range(len(B)):
    rate = int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100/int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
    exist = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(D[i]).replace('\n', '').replace('\r', '').replace(',', '').replace('–', '0').encode('utf8'))
    rate = round(rate, 3)
    E.append(rate)
    exist = format(exist, ',')
    F.append(exist)
    if G[i] != '-':
        rate10k = rate = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100000/int(str(G[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        rate10k = round(rate10k, 3)
        H.append(rate10k)
    else:
        H.append('-')

In [8]:
#import pandas to convert list to data frame

import pandas as pd


df=pd.DataFrame(A,columns=['Location'])

df['Cases']=B

df['Deaths']=C

df['Recoveries']=D

df['Death rate (%)']=E

df['Existing cases']=F

df['Population']=G

df['Infected per 100,000']=H

df.to_excel("Corona_statistics.xlsx")


df[:60]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
0,China,"80,894","3,237","69,614",4.002,"8,043","1,401,812,360",5.771
1,Italy,"31,506","2,503","2,941",7.945,"26,062","60,243,406",52.298
2,Iran,"17,361","1,135","5,389",6.538,"10,837","83,290,141",20.844
3,Spain,"13,910",624,"1,081",4.486,"12,205","47,100,396",29.533
4,Germany,"11,302",27,86,0.239,"11,189","83,149,300",13.592
5,South Korea,"8,413",84,"1,540",0.998,"6,789","51,780,579",16.247
6,France,"7,730",175,602,2.264,"6,953","67,069,000",11.525
7,United States,"6,539",116,106,1.774,"6,317","329,470,935",1.985
8,Switzerland,"3,070",27,15,0.879,"3,028","8,586,550",35.754
9,United Kingdom,"2,626",60,65,2.285,"2,501","66,435,600",3.953
10,Netherlands,"2,058",58,–,2.818,"2,000","17,445,781",11.797
11,Austria,"1,646",4,9,0.243,"1,633","8,902,600",18.489
12,Norway,"1,546",6,1,0.388,"1,539","5,367,580",28.803
13,Belgium,"1,486",10,14,0.673,"1,462","11,524,454",12.894
14,Sweden,"1,196",7,1,0.585,"1,188","10,333,456",11.574
15,Denmark,"1,092",4,–,0.366,"1,088","5,822,763",18.754
16,Japan,899,29,144,3.226,726,"126,010,000",0.713
17,Malaysia,790,2,60,0.253,728,"32,722,760",2.414
18,Diamond Princess,712,7,527,0.983,178,-,-
19,Portugal,642,2,3,0.312,637,"10,276,617",6.247
20,Canada,598,8,12,1.338,578,"37,961,548",1.575
21,Australia,565,6,43,1.062,516,"25,649,909",2.203
22,Czech Republic,464,0,3,0.000,461,"10,681,161",4.344
23,Qatar,442,0,4,0.000,438,"2,747,282",16.089
24,Israel,433,0,11,0.000,422,"9,173,250",4.72
25,Greece,387,5,14,1.292,368,"10,724,599",3.609
26,Finland,359,0,10,0.000,349,"5,527,573",6.495
27,Brazil,350,1,2,0.286,347,"211,270,518",0.166
28,Singapore,313,0,114,0.000,199,"5,703,600",5.488
29,Ireland,292,2,5,0.685,285,"4,921,500",5.933
30,Slovenia,286,1,0,0.350,285,"2,094,060",13.658
31,Pakistan,272,1,2,0.368,269,"218,983,520",0.124
32,Estonia,258,0,1,0.000,257,"1,328,360",19.422
33,Iceland,250,0,5,0.000,245,"364,260",68.632
34,Romania,246,0,19,0.000,227,"19,405,156",1.268
35,Poland,246,5,1,2.033,240,"38,386,000",0.641
36,Bahrain,242,1,88,0.413,153,"1,543,300",15.681
37,Chile,238,0,0,0.000,238,"19,107,216",1.246
38,Indonesia,227,19,11,8.370,197,"266,911,900",0.085
39,Thailand,212,1,42,0.472,169,"66,482,792",0.319
40,Luxembourg,203,2,0,0.985,201,"613,894",33.068
41,Egypt,196,6,32,3.061,158,"100,138,465",0.196
42,Philippines,193,14,4,7.254,175,"108,420,484",0.178
43,Hong Kong,181,4,92,2.210,85,"7,500,700",2.413
44,Saudi Arabia,171,0,6,0.000,165,"34,218,169",0.5
45,Iraq,164,12,41,7.317,111,"39,127,900",0.419
46,Ecuador,155,2,0,1.290,153,"17,446,584",0.888
47,India,151,3,14,1.987,134,"1,359,933,123",0.011
48,Russia,147,0,5,0.000,142,"146,745,098",0.1
49,Lebanon,133,4,4,3.008,125,"6,825,442",1.949
50,Kuwait,130,0,15,0.000,115,"4,420,110",2.941
51,San Marino,119,11,4,9.244,104,"33,574",354.441
52,Peru,117,0,1,0.000,116,"32,131,400",0.364
53,South Africa,116,0,0,0.000,116,"58,775,022",0.197
54,United Arab Emirates,113,0,26,0.000,87,"9,890,400",1.143
55,Slovakia,105,0,0,0.000,105,"5,456,362",1.924
56,Armenia,102,0,1,0.000,101,"2,957,500",3.449
57,Taiwan,100,1,22,1.000,77,"23,604,265",0.424
58,Turkey,98,1,0,1.020,97,"83,154,997",0.118
59,Mexico,93,0,4,0.000,89,"126,577,691",0.073

In [11]:
df[60:120]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
60,Panama,86,1,0,1.163,85,"4,218,808",2.038
61,Serbia,83,0,1,0.000,82,"6,963,764",1.192
62,Bulgaria,81,2,0,2.469,79,"7,000,039",1.157
63,Croatia,81,0,5,0.000,76,"4,076,246",1.987
64,Argentina,79,2,3,2.532,74,"44,938,712",0.176
65,Vietnam,76,0,16,0.000,60,"96,208,984",0.079
66,Colombia,75,0,1,0.000,74,"49,395,678",0.152
67,Algeria,72,5,10,6.944,57,"43,000,000",0.167
68,Latvia,71,0,1,0.000,70,"1,906,800",3.724
69,Brunei,68,0,0,0.000,68,"442,400",15.371
70,Albania,59,2,0,3.390,57,"2,862,427",2.061
71,Hungary,58,1,2,1.724,55,"9,772,756",0.593
72,Jordan,52,0,1,0.000,51,"10,638,536",0.489
73,Belarus,51,0,5,0.000,46,"9,413,446",0.542
74,Sri Lanka,51,0,3,0.000,48,"21,803,000",0.234
75,Costa Rica,50,0,0,0.000,50,"5,058,007",0.989
76,Uruguay,50,0,0,0.000,50,"3,518,552",1.421
77,Cyprus,49,0,0,0.000,49,"875,900",5.594
78,Morocco,49,2,1,4.082,46,"35,842,238",0.137
79,Malta,48,0,2,0.000,46,"493,559",9.725
80,Palestine,44,0,0,0.000,44,"4,976,684",0.884
81,Andorra,39,0,1,0.000,38,"77,543",50.295
82,Georgia,38,0,1,0.000,37,"3,723,464",1.021
83,North Macedonia,36,0,1,0.000,35,"2,077,132",1.733
84,Venezuela,36,0,0,0.000,36,"32,219,521",0.112
85,Cambodia,35,0,1,0.000,34,"15,288,489",0.229
86,Kazakhstan,35,0,0,0.000,35,"18,665,232",0.188
87,Azerbaijan,34,1,10,2.941,23,"10,067,108",0.338
88,Bosnia and Herzegovina,34,0,2,0.000,32,"3,301,000",1.03
89,Lithuania,33,0,1,0.000,32,"2,793,350",1.181
90,Oman,33,0,12,0.000,21,"4,664,790",0.707
91,Senegal,31,0,2,0.000,29,"16,209,125",0.191
92,Moldova,30,1,1,3.333,28,"2,681,735",1.119
93,Tunisia,29,0,0,0.000,29,"11,722,038",0.247
94,Afghanistan,22,0,1,0.000,21,"32,225,560",0.068
95,Dominican Republic,21,1,0,4.762,20,"10,358,320",0.203
96,Burkina Faso,20,1,0,5.000,19,"20,870,060",0.096
97,New Zealand,20,0,0,0.000,20,"4,971,205",0.402
98,Liechtenstein,19,0,0,0.000,19,"38,749",49.034
99,Macau,15,0,10,0.000,5,"679,600",2.207
100,Uzbekistan,15,0,0,0.000,15,"34,075,852",0.044
101,Ukraine,14,2,0,14.286,12,"41,902,416",0.033
102,Bangladesh,14,1,3,7.143,10,"168,287,530",0.008
103,Jamaica,13,0,2,0.000,11,"2,726,667",0.477
104,Maldives,13,0,0,0.000,13,"374,775",3.469
105,Kosovo,13,0,0,0.000,13,"1,795,666",0.724
106,Bolivia,12,0,0,0.000,12,"11,469,896",0.105
107,Guyana,11,1,0,9.091,10,"782,766",1.405
108,Paraguay,11,0,0,0.000,11,"7,152,703",0.154
109,Cameroon,10,0,0,0.000,10,"26,545,864",0.038
110,Honduras,9,0,0,0.000,9,"9,158,345",0.098
111,Monaco,9,0,0,0.000,9,"38,300",23.499
112,Guatemala,8,1,0,12.500,7,"16,604,026",0.048
113,Nigeria,8,0,1,0.000,7,"206,139,587",0.004
114,Rwanda,8,0,0,0.000,8,"12,374,397",0.065
115,DR Congo,7,0,0,0.000,7,"89,561,404",0.008
116,Kenya,7,0,0,0.000,7,"47,564,296",0.015
117,Northern Cyprus,7,0,0,0.000,7,"351,965",1.989
118,Trinidad and Tobago,7,0,0,0.000,7,"1,363,985",0.513
119,Ethiopia,6,0,0,0.000,6,"98,665,000",0.006

In [9]:
d = {}

for i in range(len(A)):
    d[A[i]] = (B[i],C[i],D[i],E[i],F[i],G[i],H[i])

print(d)

{'China': ('80,894\n', '3,237\n', '69,614\n', 4.002, '8,043', '1,401,812,360', 5.771), 'Italy': ('31,506\n', '2,503\n', '2,941\n', 7.945, '26,062', '60,243,406', 52.298), 'Iran': ('17,361\n', '1,135\n', '5,389\n', 6.538, '10,837', '83,290,141', 20.844), 'Spain': ('13,910\n', '624\n', '1,081\n', 4.486, '12,205', '47,100,396', 29.533), 'Germany': ('11,302\n', '27\n', '86\n', 0.239, '11,189', '83,149,300', 13.592), 'South Korea': ('8,413\n', '84\n', '1,540\n', 0.998, '6,789', '51,780,579', 16.247), 'France': ('7,730\n', '175\n', '602\n', 2.264, '6,953', '67,069,000', 11.525), 'United States': ('6,539\n', '116\n', '106\n', 1.774, '6,317', '329,470,935', 1.985), 'Switzerland': ('3,070\n', '27\n', '15\n', 0.879, '3,028', '8,586,550', 35.754), 'United Kingdom': ('2,626\n', '60\n', '65\n', 2.285, '2,501', '66,435,600', 3.953), 'Netherlands': ('2,058\n', '58\n', '–', 2.818, '2,000', '17,445,781', 11.797), 'Austria': ('1,646\n', '4\n', '9\n', 0.243, '1,633', '8,902,600', 18.489), 'Norway': ('1,546\n', '6\n', '1\n', 0.388, '1,539', '5,367,580', 28.803), 'Belgium': ('1,486\n', '10\n', '14\n', 0.673, '1,462', '11,524,454', 12.894), 'Sweden': ('1,196\n', '7\n', '1\n', 0.585, '1,188', '10,333,456', 11.574), 'Denmark': ('1,092\n', '4\n', '–', 0.366, '1,088', '5,822,763', 18.754), 'Japan': ('899\n', '29\n', '144\n', 3.226, '726', '126,010,000', 0.713), 'Malaysia': ('790\n', '2\n', '60\n', 0.253, '728', '32,722,760', 2.414), 'Diamond Princess': ('712\n', '7\n', '527\n', 0.983, '178', '-', '-'), 'Portugal': ('642\n', '2\n', '3\n', 0.312, '637', '10,276,617', 6.247), 'Canada': ('598\n', '8\n', '12\n', 1.338, '578', '37,961,548', 1.575), 'Australia': ('565\n', '6\n', '43\n', 1.062, '516', '25,649,909', 2.203), 'Czech Republic': ('464\n', '0\n', '3\n', 0.0, '461', '10,681,161', 4.344), 'Qatar': ('442\n', '0\n', '4\n', 0.0, '438', '2,747,282', 16.089), 'Israel': ('433\n', '0\n', '11\n', 0.0, '422', '9,173,250', 4.72), 'Greece': ('387\n', '5\n', '14\n', 1.292, '368', '10,724,599', 3.609), 'Finland': ('359\n', '0\n', '10\n', 0.0, '349', '5,527,573', 6.495), 'Brazil': ('350\n', '1\n', '2\n', 0.286, '347', '211,270,518', 0.166), 'Singapore': ('313\n', '0\n', '114\n', 0.0, '199', '5,703,600', 5.488), 'Ireland': ('292\n', '2\n', '5\n', 0.685, '285', '4,921,500', 5.933), 'Slovenia': ('286\n', '1\n', '0\n', 0.35, '285', '2,094,060', 13.658), 'Pakistan': ('272\n', '1\n', '2\n', 0.368, '269', '218,983,520', 0.124), 'Estonia': ('258\n', '0\n', '1\n', 0.0, '257', '1,328,360', 19.422), 'Iceland': ('250\n', '0\n', '5\n', 0.0, '245', '364,260', 68.632), 'Romania': ('246\n', '0\n', '19\n', 0.0, '227', '19,405,156', 1.268), 'Poland': ('246\n', '5\n', '1\n', 2.033, '240', '38,386,000', 0.641), 'Bahrain': ('242\n', '1\n', '88\n', 0.413, '153', '1,543,300', 15.681), 'Chile': ('238\n', '0\n', '0\n', 0.0, '238', '19,107,216', 1.246), 'Indonesia': ('227\n', '19\n', '11\n', 8.37, '197', '266,911,900', 0.085), 'Thailand': ('212\n', '1\n', '42\n', 0.472, '169', '66,482,792', 0.319), 'Luxembourg': ('203\n', '2\n', '0\n', 0.985, '201', '613,894', 33.068), 'Egypt': ('196\n', '6\n', '32\n', 3.061, '158', '100,138,465', 0.196), 'Philippines': ('193\n', '14\n', '4\n', 7.254, '175', '108,420,484', 0.178), 'Hong Kong': ('181\n', '4\n', '92\n', 2.21, '85', '7,500,700', 2.413), 'Saudi Arabia': ('171\n', '0\n', '6\n', 0.0, '165', '34,218,169', 0.5), 'Iraq': ('164\n', '12\n', '41\n', 7.317, '111', '39,127,900', 0.419), 'Ecuador': ('155\n', '2\n', '0\n', 1.29, '153', '17,446,584', 0.888), 'India': ('151\n', '3\n', '14\n', 1.987, '134', '1,359,933,123', 0.011), 'Russia': ('147\n', '0\n', '5\n', 0.0, '142', '146,745,098', 0.1), 'Lebanon': ('133\n', '4\n', '4\n', 3.008, '125', '6,825,442', 1.949), 'Kuwait': ('130\n', '0\n', '15\n', 0.0, '115', '4,420,110', 2.941), 'San Marino': ('119\n', '11\n', '4\n', 9.244, '104', '33,574', 354.441), 'Peru': ('117\n', '0\n', '1\n', 0.0, '116', '32,131,400', 0.364), 'South Africa': ('116\n', '0\n', '0\n', 0.0, '116', '58,775,022', 0.197), 'United Arab Emirates': ('113\n', '0\n', '26\n', 0.0, '87', '9,890,400', 1.143), 'Slovakia': ('105\n', '0\n', '0\n', 0.0, '105', '5,456,362', 1.924), 'Armenia': ('102\n', '0\n', '1\n', 0.0, '101', '2,957,500', 3.449), 'Taiwan': ('100\n', '1\n', '22\n', 1.0, '77', '23,604,265', 0.424), 'Turkey': ('98\n', '1\n', '0\n', 1.02, '97', '83,154,997', 0.118), 'Mexico': ('93\n', '0\n', '4\n', 0.0, '89', '126,577,691', 0.073), 'Panama': ('86\n', '1\n', '0\n', 1.163, '85', '4,218,808', 2.038), 'Serbia': ('83\n', '0\n', '1\n', 0.0, '82', '6,963,764', 1.192), 'Bulgaria': ('81\n', '2\n', '0\n', 2.469, '79', '7,000,039', 1.157), 'Croatia': ('81\n', '0\n', '5\n', 0.0, '76', '4,076,246', 1.987), 'Argentina': ('79\n', '2\n', '3\n', 2.532, '74', '44,938,712', 0.176), 'Vietnam': ('76\n', '0\n', '16\n', 0.0, '60', '96,208,984', 0.079), 'Colombia': ('75\n', '0\n', '1\n', 0.0, '74', '49,395,678', 0.152), 'Algeria': ('72\n', '5\n', '10\n', 6.944, '57', '43,000,000', 0.167), 'Latvia': ('71\n', '0\n', '1\n', 0.0, '70', '1,906,800', 3.724), 'Brunei': ('68\n', '0\n', '0\n', 0.0, '68', '442,400', 15.371), 'Albania': ('59\n', '2\n', '0\n', 3.39, '57', '2,862,427', 2.061), 'Hungary': ('58\n', '1\n', '2\n', 1.724, '55', '9,772,756', 0.593), 'Jordan': ('52\n', '0\n', '1\n', 0.0, '51', '10,638,536', 0.489), 'Belarus': ('51\n', '0\n', '5\n', 0.0, '46', '9,413,446', 0.542), 'Sri Lanka': ('51\n', '0\n', '3\n', 0.0, '48', '21,803,000', 0.234), 'Costa Rica': ('50\n', '0\n', '0\n', 0.0, '50', '5,058,007', 0.989), 'Uruguay': ('50\n', '0\n', '0\n', 0.0, '50', '3,518,552', 1.421), 'Cyprus': ('49\n', '0\n', '0\n', 0.0, '49', '875,900', 5.594), 'Morocco': ('49\n', '2\n', '1\n', 4.082, '46', '35,842,238', 0.137), 'Malta': ('48\n', '0\n', '2\n', 0.0, '46', '493,559', 9.725), 'Palestine': ('44\n', '0\n', '0\n', 0.0, '44', '4,976,684', 0.884), 'Andorra': ('39\n', '0\n', '1\n', 0.0, '38', '77,543', 50.295), 'Georgia': ('38\n', '0\n', '1\n', 0.0, '37', '3,723,464', 1.021), 'North Macedonia': ('36\n', '0\n', '1\n', 0.0, '35', '2,077,132', 1.733), 'Venezuela': ('36\n', '0\n', '0\n', 0.0, '36', '32,219,521', 0.112), 'Cambodia': ('35\n', '0\n', '1\n', 0.0, '34', '15,288,489', 0.229), 'Kazakhstan': ('35\n', '0\n', '0\n', 0.0, '35', '18,665,232', 0.188), 'Azerbaijan': ('34\n', '1\n', '10\n', 2.941, '23', '10,067,108', 0.338), 'Bosnia and Herzegovina': ('34\n', '0\n', '2\n', 0.0, '32', '3,301,000', 1.03), 'Lithuania': ('33\n', '0\n', '1\n', 0.0, '32', '2,793,350', 1.181), 'Oman': ('33\n', '0\n', '12\n', 0.0, '21', '4,664,790', 0.707), 'Senegal': ('31\n', '0\n', '2\n', 0.0, '29', '16,209,125', 0.191), 'Moldova': ('30\n', '1\n', '1\n', 3.333, '28', '2,681,735', 1.119), 'Tunisia': ('29\n', '0\n', '0\n', 0.0, '29', '11,722,038', 0.247), 'Afghanistan': ('22\n', '0\n', '1\n', 0.0, '21', '32,225,560', 0.068), 'Dominican Republic': ('21\n', '1\n', '0\n', 4.762, '20', '10,358,320', 0.203), 'Burkina Faso': ('20\n', '1\n', '0\n', 5.0, '19', '20,870,060', 0.096), 'New Zealand': ('20\n', '0\n', '0\n', 0.0, '20', '4,971,205', 0.402), 'Liechtenstein': ('19\n', '0\n', '0\n', 0.0, '19', '38,749', 49.034), 'Macau': ('15\n', '0\n', '10\n', 0.0, '5', '679,600', 2.207), 'Uzbekistan': ('15\n', '0\n', '0\n', 0.0, '15', '34,075,852', 0.044), 'Ukraine': ('14\n', '2\n', '0\n', 14.286, '12', '41,902,416', 0.033), 'Bangladesh': ('14\n', '1\n', '3\n', 7.143, '10', '168,287,530', 0.008), 'Jamaica': ('13\n', '0\n', '2\n', 0.0, '11', '2,726,667', 0.477), 'Maldives': ('13\n', '0\n', '0\n', 0.0, '13', '374,775', 3.469), 'Kosovo': ('13\n', '0\n', '0\n', 0.0, '13', '1,795,666', 0.724), 'Bolivia': ('12\n', '0\n', '0\n', 0.0, '12', '11,469,896', 0.105), 'Guyana': ('11\n', '1\n', '0\n', 9.091, '10', '782,766', 1.405), 'Paraguay': ('11\n', '0\n', '0\n', 0.0, '11', '7,152,703', 0.154), 'Cameroon': ('10\n', '0\n', '0\n', 0.0, '10', '26,545,864', 0.038), 'Honduras': ('9\n', '0\n', '0\n', 0.0, '9', '9,158,345', 0.098), 'Monaco': ('9\n', '0\n', '0\n', 0.0, '9', '38,300', 23.499), 'Guatemala': ('8\n', '1\n', '0\n', 12.5, '7', '16,604,026', 0.048), 'Nigeria': ('8\n', '0\n', '1\n', 0.0, '7', '206,139,587', 0.004), 'Rwanda': ('8\n', '0\n', '0\n', 0.0, '8', '12,374,397', 0.065), 'DR Congo': ('7\n', '0\n', '0\n', 0.0, '7', '89,561,404', 0.008), 'Kenya': ('7\n', '0\n', '0\n', 0.0, '7', '47,564,296', 0.015), 'Northern Cyprus': ('7\n', '0\n', '0\n', 0.0, '7', '351,965', 1.989), 'Trinidad and Tobago': ('7\n', '0\n', '0\n', 0.0, '7', '1,363,985', 0.513), 'Ethiopia': ('6\n', '0\n', '0\n', 0.0, '6', '98,665,000', 0.006), 'Ghana': ('6\n', '0\n', '0\n', 0.0, '6', '30,280,811', 0.02), 'Ivory Coast': ('6\n', '0\n', '1\n', 0.0, '5', '25,823,071', 0.023), 'Mongolia': ('6\n', '0\n', '0\n', 0.0, '6', '3,308,132', 0.181), 'Cuba': ('5\n', '0\n', '0\n', 0.0, '5', '11,209,628', 0.045), 'Seychelles': ('4\n', '0\n', '0\n', 0.0, '4', '97,625', 4.097), 'Kyrgyzstan': ('3\n', '0\n', '0\n', 0.0, '3', '6,523,500', 0.046), 'Tanzania': ('3\n', '0\n', '0\n', 0.0, '3', '55,890,747', 0.005), 'Barbados': ('2\n', '0\n', '0\n', 0.0, '2', '287,025', 0.697), 'Benin': ('2\n', '0\n', '0\n', 0.0, '2', '11,733,059', 0.017), 'Liberia': ('2\n', '0\n', '0\n', 0.0, '2', '4,475,353', 0.045), 'Montenegro': ('2\n', '0\n', '0\n', 0.0, '2', '622,359', 0.321), 'Namibia': ('2\n', '0\n', '0\n', 0.0, '2', '2,458,936', 0.081), 'Saint Lucia': ('2\n', '0\n', '0\n', 0.0, '2', '178,696', 1.119), 'Sudan': ('2\n', '1\n', '0\n', 50.0, '1', '42,353,615', 0.005), 'Zambia': ('2\n', '0\n', '0\n', 0.0, '2', '17,381,168', 0.012), 'Antigua and Barbuda': ('1\n', '0\n', '0\n', 0.0, '1', '96,453', 1.037), 'Bahamas': ('1\n', '0\n', '0\n', 0.0, '1', '385,340', 0.26), 'Bhutan': ('1\n', '0\n', '0\n', 0.0, '1', '741,672', 0.135), 'Central African Republic': ('1\n', '0\n', '0\n', 0.0, '1', '5,496,011', 0.018), 'Republic of the Congo': ('1\n', '0\n', '0\n', 0.0, '1', '-', '-'), 'Djibouti': ('1\n', '0\n', '0\n', 0.0, '1', '1,078,373', 0.093), 'Equatorial Guinea': ('1\n', '0\n', '0\n', 0.0, '1', '1,358,276', 0.074), 'Eswatini': ('1\n', '0\n', '0\n', 0.0, '1', '1,093,238', 0.091), 'Gabon': ('1\n', '0\n', '0\n', 0.0, '1', '2,172,579', 0.046), 'Gambia': ('1\n', '0\n', '0\n', 0.0, '1', '2,347,706', 0.043), 'Guinea': ('1\n', '0\n', '0\n', 0.0, '1', '12,218,357', 0.008), 'Mauritania': ('1\n', '0\n', '0\n', 0.0, '1', '4,077,347', 0.025), 'St. Vincent ': ('1\n', '0\n', '0\n', 0.0, '1', '-', '-'), 'Somalia': ('1\n', '0\n', '0\n', 0.0, '1', '15,893,219', 0.006), 'Suriname': ('1\n', '0\n', '0\n', 0.0, '1', '581,372', 0.172), 'Togo': ('1\n', '0\n', '0\n', 0.0, '1', '7,538,000', 0.013), 'Vatican City': ('1\n', '0\n', '0\n', 0.0, '1', '799', 125.156), 'Nepal': ('1\n', '0\n', '1\n', 0.0, '0', '29,609,623', 0.003)}