In [1]:
#import the library used to query a website
from urllib.request import urlopen

#specify the url
wiki = "https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic_by_country_and_territory"
wiki2 = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

#Query the website and return the html to the variable 'page'
page = urlopen(wiki)
page2 = urlopen(wiki2)

#import the Beautiful soup functions to parse the data returned from the website
from bs4 import BeautifulSoup

#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page)
soup2 = BeautifulSoup(page2)

In [2]:
right_table=soup.find('table', class_='wikitable plainrowheaders sortable')
right_table2=soup2.find('table', class_='wikitable sortable')

In [3]:
A=[]

for row in right_table.findAll("tr"):
    cells = row.findAll('a')
    #print(cells)
    if len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5 or len(cells)==6:
        if cells[0].find(text=True) == None:
            A.append(cells[1].find(text=True))
        else:
            A.append(cells[0].find(text=True))
    
del(A[0])
del(A[1])
del(A[-1])
A[0] = 'China'

In [4]:
A2=[]

for row in right_table2.findAll("tr"):
    cells = row.findAll('a')
    if len(cells)==1 or len(cells)==2 or len(cells)==3 or len(cells)==4 or len(cells)==5:
        if cells[0].find(text=True) == None:
            A2.append(cells[1].find(text=True))
        else:
            A2.append(cells[0].find(text=True))
    
del(A2[-1])

#Generate lists
B2=[]


for row in right_table2.findAll("tr"):
    cells = row.findAll("td")
    if len(cells)==6: #Only extract table body not heading
        B2.append(cells[2].find(text=True))

In [5]:
#Generate lists
B=[]
C=[]
D=[]

for row in right_table.findAll("tr"):
    cells = row.findAll("td")
    #print(cells)
    if len(cells)==4: #Only extract table body not heading
        print(cells[0].find(text=True))
        B.append(cells[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))

80,928

35,713

18,407

17,395

14,259

,

9,134

8,565

3,438

2,626

2,468

2,013

1,795

1,738

1,418

1,206

923

900

785

727

712

709

631

529

529

452

418

400

384

366

345

342

335

330

325

319

309

277

272

269

267

238

217

210

208

199

191

173

168

164

150

149

148

145

144

140

123

122

118

109

108

102

99

97

97

94

86

79

76

75

73

73

69

64

58

58

56

53

53

51

49

48

47

45

44

40

39

37

36

36

36

36

34

34

29

28

28

27

23

22

20

18

17

16

15

15

14

13

13

13

12

11

11

11

9

9

9

9

8

8

12

7

6

6

6

6

4

4

3

3

3

2

2

2

2

2

2

2

2

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

1

In [6]:
G=[]

for i,country in enumerate(A):
    if A[i] in A2:
        idx = A2.index(A[i])
        population = B2[idx]
        G.append(population)
    else:
        G.append('-')

In [7]:
E=[]
F=[]
H=[]

for i in range(len(B)):
    if str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit() and str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit():
        rate = int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100/int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        exist = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(C[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8')) - int(str(D[i]).replace('\n', '').replace('\r', '').replace(',', '').replace('â€“', '0').encode('utf8'))
        exist = format(exist, ',')
        rate = round(rate, 3)
    else:
        rate = '-'
    E.append(rate)
    
    F.append(exist)
    if G[i] != '-' and str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8').isdigit():
        rate10k = int(str(B[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))*100000/int(str(G[i]).replace('\n', '').replace('\r', '').replace(',', '').encode('utf8'))
        rate10k = round(rate10k, 3)
        H.append(rate10k)
    else:
        H.append('-')

In [8]:
#import pandas to convert list to data frame

import pandas as pd


df=pd.DataFrame(A,columns=['Location'])

df['Cases']=B

df['Deaths']=C

df['Recoveries']=D

df['Death rate (%)']=E

df['Existing cases']=F

df['Population']=G

df['Infected per 100,000']=H

df.to_excel("Corona_statistics.xlsx")


df[:60]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
0,China,"80,928","3,245","70,420",4.01,"7,263","1,401,812,360",5.773
1,Italy,"35,713","2,978","4,025",8.339,"28,710","60,243,406",59.281
2,Iran,"18,407","1,284","5,710",6.976,"11,413","83,290,141",22.1
3,Spain,"17,395",803,"1,107",4.616,"15,485","47,100,396",36.932
4,Germany,"14,259",43,113,0.302,"14,103","83,149,300",17.149
5,United States,",",160,108,-,"14,103","329,470,935",-
6,France,"9,134",264,602,2.89,"8,268","67,069,000",13.619
7,South Korea,"8,565",91,"1,947",1.062,"6,527","51,780,579",16.541
8,Switzerland,"3,438",33,15,0.96,"3,390","8,586,550",40.039
9,United Kingdom,"2,626",103,65,3.922,"2,458","66,435,600",3.953
10,Netherlands,"2,468",77,â€“,3.12,"2,391","17,445,781",14.147
11,Austria,"2,013",6,9,0.298,"1,998","8,902,600",22.611
12,Belgium,"1,795",21,31,1.17,"1,743","11,524,454",15.576
13,Norway,"1,738",7,1,0.403,"1,730","5,367,580",32.38
14,Sweden,"1,418",11,16,0.776,"1,391","10,333,456",13.722
15,Denmark,"1,206",6,â€“,0.498,"1,200","5,822,763",20.712
16,Japan,923,32,191,3.467,700,"126,010,000",0.732
17,Malaysia,900,2,75,0.222,823,"32,722,760",2.75
18,Portugal,785,3,3,0.382,779,"10,276,617",7.639
19,Canada,727,9,11,1.238,707,"37,961,548",1.915
20,Diamond Princess,712,8,551,1.124,153,-,-
21,Australia,709,6,46,0.846,657,"25,649,909",2.764
22,Czech Republic,631,0,3,0,628,"10,681,161",5.908
23,Brazil,529,4,2,0.756,523,"211,270,518",0.25
24,Israel,529,0,12,0,517,"9,173,250",5.767
25,Qatar,452,0,4,0,448,"2,747,282",16.453
26,Greece,418,5,14,1.196,399,"10,724,599",3.898
27,Finland,400,0,10,0,390,"5,527,573",7.236
28,Pakistan,384,2,13,0.521,369,"218,983,520",0.175
29,Ireland,366,2,5,0.546,359,"4,921,500",7.437
30,Singapore,345,0,124,0,221,"5,703,600",6.049
31,Chile,342,0,0,0,342,"19,107,216",1.79
32,Luxembourg,335,4,0,1.194,331,"613,894",54.57
33,Iceland,330,0,5,0,325,"364,260",90.595
34,Poland,325,5,13,1.538,307,"38,386,000",0.847
35,Slovenia,319,1,0,0.313,318,"2,094,060",15.234
36,Indonesia,309,25,15,8.091,269,"266,911,900",0.116
37,Romania,277,0,25,0,252,"19,405,156",1.427
38,Thailand,272,1,42,0.368,229,"66,482,792",0.409
39,Bahrain,269,1,100,0.372,168,"1,543,300",17.43
40,Estonia,267,0,1,0,266,"1,328,360",20.1
41,Saudi Arabia,238,0,8,0,230,"34,218,169",0.696
42,Philippines,217,17,8,7.834,192,"108,420,484",0.2
43,Egypt,210,6,32,2.857,172,"100,138,465",0.21
44,Hong Kong,208,4,98,1.923,106,"7,500,700",2.773
45,Russia,199,0,5,0,194,"146,745,098",0.136
46,Turkey,191,2,0,1.047,189,"83,154,997",0.23
47,India,173,4,20,2.312,149,"1,359,933,123",0.013
48,Ecuador,168,3,1,1.786,164,"17,446,584",0.963
49,Iraq,164,12,41,7.317,111,"39,127,900",0.419
50,South Africa,150,0,0,0,150,"58,775,022",0.255
51,Lebanon,149,4,4,2.685,141,"6,825,442",2.183
52,Kuwait,148,0,18,0,130,"4,420,110",3.348
53,Peru,145,0,1,0,144,"32,131,400",0.451
54,San Marino,144,14,4,9.722,126,"33,574",428.903
55,United Arab Emirates,140,0,31,0,109,"9,890,400",1.416
56,Slovakia,123,0,0,0,123,"5,456,362",2.254
57,Armenia,122,0,1,0,121,"2,957,500",4.125
58,Mexico,118,0,4,0,114,"126,577,691",0.093
59,Panama,109,1,0,0.917,108,"4,218,808",2.584

In [9]:
df[60:120]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
60,Taiwan,108,1,26,0.926,81,"23,604,265",0.458
61,Colombia,102,0,1,0,101,"49,395,678",0.206
62,Croatia,99,1,5,1.01,93,"4,076,246",2.429
63,Argentina,97,3,3,3.093,91,"44,938,712",0.216
64,Serbia,97,0,1,0,96,"6,963,764",1.393
65,Bulgaria,94,3,0,3.191,91,"7,000,039",1.343
66,Latvia,86,0,1,0,85,"1,906,800",4.51
67,Uruguay,79,0,0,0,79,"3,518,552",2.245
68,Vietnam,76,0,16,0,60,"96,208,984",0.079
69,Algeria,75,7,32,9.333,36,"43,000,000",0.174
70,Brunei,73,0,0,0,73,"442,400",16.501
71,Hungary,73,1,2,1.37,70,"9,772,756",0.747
72,Costa Rica,69,1,0,1.449,68,"5,058,007",1.364
73,Albania,64,2,0,3.125,62,"2,862,427",2.236
74,Cyprus,58,0,0,0,58,"875,900",6.622
75,Morocco,58,2,1,3.448,55,"35,842,238",0.162
76,Jordan,56,0,1,0,55,"10,638,536",0.526
77,Andorra,53,0,1,0,52,"77,543",68.349
78,Sri Lanka,53,0,3,0,50,"21,803,000",0.243
79,Belarus,51,0,5,0,46,"9,413,446",0.542
80,North Macedonia,49,0,1,0,48,"2,077,132",2.359
81,Malta,48,0,2,0,46,"493,559",9.725
82,Palestine,47,0,0,0,47,"4,976,684",0.944
83,Bosnia and Herzegovina,45,0,2,0,43,"3,301,000",1.363
84,Kazakhstan,44,0,0,0,44,"18,665,232",0.236
85,Georgia,40,0,1,0,39,"3,723,464",1.074
86,Oman,39,0,13,0,26,"4,664,790",0.836
87,Cambodia,37,0,1,0,36,"15,288,489",0.242
88,Lithuania,36,0,1,0,35,"2,793,350",1.289
89,Moldova,36,1,1,2.778,34,"2,681,735",1.342
90,Senegal,36,0,2,0,34,"16,209,125",0.222
91,Venezuela,36,0,0,0,36,"32,219,521",0.112
92,Azerbaijan,34,1,10,2.941,23,"10,067,108",0.338
93,Dominican Republic,34,2,0,5.882,32,"10,358,320",0.328
94,Tunisia,29,0,1,0,28,"11,722,038",0.247
95,Liechtenstein,28,0,0,0,28,"38,749",72.26
96,New Zealand,28,0,0,0,28,"4,971,205",0.563
97,Burkina Faso,27,1,0,3.704,26,"20,870,060",0.129
98,Uzbekistan,23,0,0,0,23,"34,075,852",0.067
99,Afghanistan,22,0,1,0,21,"32,225,560",0.068
100,Northern Cyprus,20,0,0,0,20,"351,965",5.682
101,Bangladesh,18,1,3,5.556,14,"168,287,530",0.011
102,Macau,17,0,10,0,7,"679,600",2.501
103,Ukraine,16,2,0,12.5,14,"41,902,416",0.038
104,Bolivia,15,0,0,0,15,"11,469,896",0.131
105,Jamaica,15,1,2,6.667,12,"2,726,667",0.55
106,DR Congo,14,0,0,0,14,"89,561,404",0.016
107,Cameroon,13,0,0,0,13,"26,545,864",0.049
108,Maldives,13,0,0,0,13,"374,775",3.469
109,Kosovo,13,0,0,0,13,"1,795,666",0.724
110,Honduras,12,0,0,0,12,"9,158,345",0.131
111,Cuba,11,1,0,9.091,10,"11,209,628",0.098
112,Paraguay,11,0,0,0,11,"7,152,703",0.154
113,Rwanda,11,0,0,0,11,"12,374,397",0.089
114,Ghana,9,0,0,0,9,"30,280,811",0.03
115,Ivory Coast,9,0,1,0,8,"25,823,071",0.035
116,Monaco,9,0,0,0,9,"38,300",23.499
117,Trinidad and Tobago,9,0,0,0,9,"1,363,985",0.66
118,Guatemala,8,1,0,12.5,7,"16,604,026",0.048
119,Montenegro,8,0,0,0,8,"622,359",1.285

In [10]:
df[120:-1]

,Location,Cases,Deaths,Recoveries,Death rate (%),Existing cases,Population,"Infected per 100,000"
120,Nigeria,12,0,1,0,11,"206,139,587",0.006
121,Kenya,7,0,0,0,7,"47,564,296",0.015
122,Ethiopia,6,0,0,0,6,"98,665,000",0.006
123,Mongolia,6,0,0,0,6,"3,308,132",0.181
124,Seychelles,6,0,0,0,6,"97,625",6.146
125,Tanzania,6,0,0,0,6,"55,890,747",0.011
126,Equatorial Guinea,4,0,0,0,4,"1,358,276",0.294
127,Guyana,4,1,0,25,3,"782,766",0.511
128,Gabon,3,0,0,0,3,"2,172,579",0.138
129,Kyrgyzstan,3,0,0,0,3,"6,523,500",0.046
130,Mauritius,3,0,0,0,3,"1,265,985",0.237
131,Barbados,2,0,0,0,2,"287,025",0.697
132,Benin,2,0,0,0,2,"11,733,059",0.017
133,Liberia,2,0,0,0,2,"4,475,353",0.045
134,Mauritania,2,0,0,0,2,"4,077,347",0.049
135,Namibia,2,0,0,0,2,"2,458,936",0.081
136,Saint Lucia,2,0,0,0,2,"178,696",1.119
137,Sudan,2,1,0,50,1,"42,353,615",0.005
138,Zambia,2,0,0,0,2,"17,381,168",0.012
139,Antigua and Barbuda,1,0,0,0,1,"96,453",1.037
140,Bahamas,1,0,0,0,1,"385,340",0.26
141,Bhutan,1,0,0,0,1,"741,672",0.135
142,Chad,1,0,0,0,1,"15,692,969",0.006
143,Central African Republic,1,0,0,0,1,"5,496,011",0.018
144,Republic of the Congo,1,0,0,0,1,-,-
145,Djibouti,1,0,0,0,1,"1,078,373",0.093
146,El Salvador,1,0,0,0,1,"6,486,201",0.015
147,Eswatini,1,0,0,0,1,"1,093,238",0.091
148,Fiji,1,0,0,0,1,"884,887",0.113
149,Gambia,1,0,0,0,1,"2,347,706",0.043
150,Guinea,1,0,0,0,1,"12,218,357",0.008
151,Nepal,1,0,1,0,0,"29,609,623",0.003
152,Nicaragua,1,0,0,0,1,"6,460,411",0.015
153,St. Vincent,1,0,0,0,1,-,-
154,Somalia,1,0,0,0,1,"15,893,219",0.006
155,Suriname,1,0,0,0,1,"581,372",0.172
156,Togo,1,0,0,0,1,"7,538,000",0.013

In [11]:
d = {}

for i in range(len(A)):
    d[A[i]] = (B[i],C[i],D[i],E[i],F[i],G[i],H[i])